# Generated by Django 4.0.3 on 2022-04-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='essaytheme',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
